% data.Log contains:
% data.Log.data with 
%   * xwhole 12x
%   * u_input 4x 
%   * delta_u 3x 
%   * u_z 1x 
%   * U 4x
% data.RefAltitude 
%   * roll, pitch, azimuth

% associated with simulink.mdl/Testbed\ Logger

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Quantity Generally Available
%% (24x)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

time = data.RefAttitude.time;

phi = data.RefAttitude.data(:,1);
theta = data.RefAttitude.data(:,2);
psi = data.RefAttitude.data(:,3);
var_struct_euler =  struct(...
'phi', phi, ...
'theta', theta, ...
'psi', psi );

modelx = data.Log.data(:,1);
modely = data.Log.data(:,2);
modelz = data.Log.data(:,3);

modelxdot = data.Log.data(:,4);
modelydot = data.Log.data(:,5);
modelzdot = data.Log.data(:,6);

observer_phi = data.Log.data(:,7);
observer_theta = data.Log.data(:,8);
observer_psi = data.Log.data(:,9);

observer_angularx = data.Log.data(:,10);
observer_angulary = data.Log.data(:,11);
observer_angularz = data.Log.data(:,12);

Fz = data.Log.data(:,13);
Mx = data.Log.data(:,14);
My = data.Log.data(:,15);
Mz = data.Log.data(:,16);

deltau1 = data.Log.data(:,17);
deltau2 = data.Log.data(:,18);
deltau3 = data.Log.data(:,19);

uz = data.Log.data(:,20);

U1 = data.Log.data(:,21);
U2 = data.Log.data(:,22);
U3 = data.Log.data(:,23);
U4 = data.Log.data(:,24);

real_modelx = data.Log.data(:,25);
real_modely = data.Log.data(:,26);
real_modelz = data.Log.data(:,27);

real_modelxdot = data.Log.data(:,28);
real_modelydot = data.Log.data(:,29);
real_modelzdot = data.Log.data(:,30);

real_observer_phi = data.Log.data(:,31);
real_observer_theta = data.Log.data(:,32);
real_observer_psi = data.Log.data(:,33);

real_observer_angularx = data.Log.data(:,34);
real_observer_angulary = data.Log.data(:,35);
real_observer_angularz = data.Log.data(:,36);

var_struct_modelxyz =  struct(...
'modelx', modelx,  ...
'modely', modely,  ...
'modelz', modelz  ...
);

var_struct_modelxyzdot =  struct(...
'modelxdot', modelxdot,  ...
'modelydot', modelydot,  ...
'modelzdot', modelzdot  ...
);

var_struct_observerEuler =  struct(...
'observerphi', observer_phi,  ...
'observertheta', observer_theta, ...
'observerpsi', observer_psi );


var_struct_observerAngular =  struct(...
'observerangularx', observer_angularx,  ...
'observerangulary', observer_angulary, ...
'observerangularz', observer_angularz );

var_struct_M =  struct(...
'Mx', Mx, ...
'My', My, ...
'Mz', Mz, ...,
'Fz', Fz);

var_struct_deltau =  struct(...
'deltau1', deltau1, ...
'deltau2', deltau2, ...
'deltau3', deltau3, ...
'uz', uz );

var_struct_U =  struct(...
'U1', U1, ...
'U2', U2, ...
'U3', U3, ...
'U4', U4 );


var_struct_modeloutput =  struct(...
'modelx', modelx,  ...
'modely', modely,  ...
'modelz', modelz,  ...
'observerpsi', observer_psi );


var_struct_MotFreq =  struct(...
'FreqFront', data.MotStat.data(:,3), ...
'FreqRight', data.MotStat.data(:,4), ...
'FreqRear', data.MotStat.data(:,5), ...
'FreqLeft', data.MotStat.data(:,6) );

var_struct_MotCom =  struct(...
'PWMFront', data.MotCom.data(:,1), ...
'PWMRight', data.MotCom.data(:,2), ...
'PWMRear', data.MotCom.data(:,3), ...
'PWMLeft', data.MotCom.data(:,4) );

var_struct_real_modelxyz =  struct(...
'real_modelx', real_modelx,  ...
'real_modely', real_modely,  ...
'real_modelz', real_modelz  ...
);

var_struct_real_modelxyzdot =  struct(...
'real_modelxdot', real_modelxdot,  ...
'real_modelydot', real_modelydot,  ...
'real_modelzdot', real_modelzdot  ...
);

var_struct_real_observerEuler =  struct(...
'real_observerphi', real_observer_phi,  ...
'real_observertheta', real_observer_theta, ...
'real_observerpsi', real_observer_psi );


var_struct_real_observerAngular =  struct(...
'real_observerangularx', real_observer_angularx,  ...
'real_observerangulary', real_observer_angulary, ...
'real_observerangularz', real_observer_angularz );



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Quantity in Cascade Controller
%% (6x)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


Fz_wo_saturation = data.Log.data(:,37);
Mx_wo_saturation = data.Log.data(:,38);
My_wo_saturation = data.Log.data(:,39);
Mz_wo_saturation = data.Log.data(:,40);

var_struct_u_wo_saturation =  struct(...
'Fz_wo_saturation', Fz_wo_saturation,  ...
'Mx_wo_saturation', Mx_wo_saturation,  ...
'My_wo_saturation', My_wo_saturation,  ...
'Mz_wo_saturation', Mz_wo_saturation);

phi_cmd  = data.Log.data(:,41);
theta_cmd  = data.Log.data(:,42);
var_struct_angle_cmd =  struct(...
'phi_cmd', phi_cmd,  ...
'theta_cmd', theta_cmd);
