function save_hil_plots(name, data)

%get_command;

time = data.RefAttitude.time;
t_cutoff = 50;
time_trimmed = [ time(1):0.01:t_cutoff];

if (length(time) < length(time_trimmed))
    clear time_trimmed;
    time_trimmed = time;
end

%format_command;
plot_struct_hil_for_thesis_multi(name,...
time_trimmed, data.var_struct_command, data.var_struct_modeloutput);

plot_struct_hil_for_thesis(name,...
time, data.var_struct_MotFreq, data.var_struct_MotCom);
% plot the euler angles and angular velocity from observer
plot_struct_hil_for_thesis(name,...
time, data.var_struct_observerEuler, data.var_struct_observerAngular);

% Figure one
plot_struct_hil_for_thesis( name ,...
time, ...
 data.var_struct_euler,... 
 data.var_struct_M, ...
 data.var_struct_deltau, ...
 data.var_struct_U );

plot_struct_hil_for_thesis(name,...
time, ...
 data.var_struct_euler,... 
data.var_struct_observerEuler);

plot_struct_hil_for_thesis(name, time, ...
data.var_struct_modelxyz, ...
data.var_struct_modelxyzdot, ...
data.var_struct_observerEuler, ...
data.var_struct_observerAngular );

plot_struct_hil_for_thesis(name, time, ...
data.var_struct_real_modelxyz, ...
data.var_struct_real_modelxyzdot );

plot_struct_hil_for_thesis(name, time, ...
data.var_struct_observerEuler, ...
data.var_struct_real_observerEuler, ...
data.var_struct_observerAngular, ...
data.var_struct_real_observerAngular );

%plot_struct_hil_for_thesis(name,...
%time, ...
%data.var_struct_modeloutput, ...
%data.var_struct_yref, data.var_struct_command );

plot_struct_hil_for_thesis(name,...
time, ...
data.var_struct_nucorrected, ...
data.var_struct_nuhedge );

plot_struct_hil_for_thesis(name, time, ...
data.var_struct_P_modelxyz, ...
data.var_struct_P_modelxyzdot);

plot_struct_hil_for_thesis(name, time, ...
data.var_struct_EstError_modelxyz, ...
data.var_struct_EstError_modelxyzdot, ...
data.var_struct_Error_observerEuler, ...
data.var_struct_Error_observerAngular );

end
