classdef AlphaBeta
    properties
        handles = struct();
        maxAlpha = 30;
        maxBeta = 30;
    end
    
    methods
        function obj = AlphaBeta(h)
            obj.handles.axis = h;
                        
            set(obj.handles.axis, ...
                'PlotBoxAspectRatio', [1 1 1], ...
                'DataAspectRatio', [1 1 1], ...
                'Color', 'white', ...
                'Box', 'on', ...
                'XLim', [-obj.maxBeta  obj.maxBeta], ...
                'YLim', [-obj.maxAlpha obj.maxAlpha], ...
                'XGrid', 'on', 'YGrid', 'on', ...
                'XTickLabel', [], 'YTickLabel', [], ...
                'NextPlot', 'replacechildren' ...
            );
        
            obj.handles.marker = plot(obj.handles.axis, 0, 0, 'r.', 'MarkerSize', 20);
        end
        
        function update(obj, alpha, beta)
            set(obj.handles.marker, 'XData', beta / pi * 180, 'YData', alpha / pi * 180);
        end
    end
end
